---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos" tag="7"
    - image="redhat" tag="7"
    - image="centos"
    - image="redhat"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "JF8+j5vPtAmnRMoC0BxWfm/AVfKwu5Ic6+G2cTAMSU/rDesrqc6u4XByR5J1URxF3g+NYts0fKV/sL92Lw4L676sPl8atarlb/jWhVptBGJ0KWm23fIC8zl87XJYBKFb/gLugBwftruBwEU0zi35sfmyRITzv7XmBgZVgI4d4tLbDc0D9C8qibvtzKdDsNe/q0bBmaBxmF8xOgZ+nyvkCCmqMVlHJ13sr8ciNLPFhfQM9bG3Yahzd0dgGMXXYtGdIE1J3UGCuGpXyv4r8NjW9YgDCbErkhBYACjnLqnvLlLSJESlPGbR7BbNI1FDMovv0mlcN9/POALU7ccB3zLyKUhQqqeNGDJN5Ms74Rm07NCpyoQeOHxh8yN5LHy1qNTzOsS2AKZR7ZQK9EXso1K4y4WjcAngIPWHILL66uFdOuPAG339Mjaj1HhbKSJXTytgsMJrGjeuE/8kya9yEMhpRWAwtEiKIXw6tJVKKEpdgn5Ee1Wd7FEIkZ7F3p5nDOG0PBXFnrpSLEbhXP99QE361SpDmQn0++fJdL/sONj2zab4OD9DSflsLGXVDnxH8PLURvnaL14xrLfp0aeKJmQcJ6aIdcKGwzpWETewrc/ECEFy1SvHjhj6q8pwuKKp9+lAE47cVzNfeTldYmgnA0aOVQgbkrTfWMMcRG6Z29U8dLM="
  email: false
