---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-alternatives
      alternatives_list:
        - name: my_alternative_grep
          link: /usr/bin/my_grep
          path: /usr/bin/grep
