---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.alternatives
      alternatives_list:
        - name: my_alternative_fake_binary
          link: /bin/my_alternative_fake_binary
          path: /bin/my_fake_binary
