---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: make a fake binary
      file:
        path: /bin/my_fake_binary
        state: touch
