---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-alternatives
      alternatives_list:
        - name: My_alternative_fake_binary
          link: /bin/my_alternative_fake_binary
          path: /bin/my_fake_binary
